# Generated by Django 6.0.6 on 2026-06-16 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaMuseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(verbose_name='Nombre y Apellido del guia')),
                ('anios_experiencia_guia', models.IntegerField(verbose_name='Años de experiencia')),
                ('idiomas_hablados', models.CharField(verbose_name='Idiomas que puede hablar el guia')),
            ],
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(unique=True, verbose_name='Nombre del Museo')),
                ('ciudad', models.CharField(verbose_name='Ciudad donde se ubica el museo')),
                ('anio_fundacion', models.IntegerField(verbose_name='Año de fundacion')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_exhibicion', models.CharField(verbose_name='Titulo de la exhibicion')),
                ('duaracion_meses', models.IntegerField(verbose_name='Duracion de la exhibicion en meses')),
                ('costo_produccion', models.FloatField(verbose_name='Costo total de la produccion')),
                ('tematica', models.CharField(verbose_name='Tematica proncipal de la exhibicion')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibiciones', to='institucion.guiamuseo')),
            ],
        ),
        migrations.AddField(
            model_name='guiamuseo',
            name='museo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='institucion.museo'),
        ),
    ]
