# Generated by Django 6.0.6 on 2026-06-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibicion',
            old_name='duaracion_meses',
            new_name='duracion_meses',
        ),
    ]
